[package]
name = "yarig"
version = "0.16.3"
edition = "2024"
rust-version = "1.85"
license = "MIT"
description = "A register interface generator"
repository = "https://github.com/TheClams/yarig"
readme = "Readme.md"
categories = ["command-line-utilities", "hardware-support", "parser-implementations"]
keywords = ["register", "verilog", "rif"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = "1.0.218"
serde_derive = "1.0.218"
toml = "0.8.20"
winnow = "0.7"
yarig_macro = { version = "^0", path = "./yarig_macro" }
latex2mathml = { version = "^0"}

[patch.crates-io]
latex2mathml = { git = "https://github.com/TheClams/latex2mathml.git", tag = "0.3.0"}

[profile.release]
strip = true # Strip symbols from the binary
