use std::collections::HashMap;

use crate::{generator::casing::{Casing, ToCasing}, rifgen::{EnumDef, FieldSwKind}};

use super::{
    gen_common::{GeneratorBase, GeneratorBaseSetting, GeneratorCore},
    trait_doc::{CellKind, GeneratorDoc, TableKind}
};

/// Kind of paragraph used in the dicument
#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
enum PgfKind {
    Anchor, Heading2, Heading3,
    RifmuxTable, MappingTable, RegTable,
    TableTitle, TableHeading, TableCell
}

#[allow(dead_code)]
pub struct GeneratorMif {
    /// Base structure of all generators
    core: GeneratorCore,
    /// Flag when current document is for a RIFMux
    is_rifmux: bool,
    /// Flag when current document is for a RIFMux
    multipage: bool,
    /// Flag when current document is for a RIFMux
    pgf_name: HashMap<PgfKind, String>,
    /// Table index
    tbl_idx: usize
}

#[allow(dead_code)]
impl GeneratorMif {

    pub fn new(setting: GeneratorBaseSetting) -> Self {
        let mut pgf_name = HashMap::new();
        pgf_name.insert(PgfKind::Anchor      , "Body".to_owned());
        pgf_name.insert(PgfKind::Heading2    , "2heading".to_owned());
        pgf_name.insert(PgfKind::Heading3    , "3headingReg".to_owned());
        pgf_name.insert(PgfKind::RifmuxTable , "Mapping Table".to_owned());
        pgf_name.insert(PgfKind::MappingTable, "Mapping Table".to_owned());
        pgf_name.insert(PgfKind::RegTable    , "Register".to_owned());
        pgf_name.insert(PgfKind::TableTitle  , "TableTitle".to_owned());
        pgf_name.insert(PgfKind::TableHeading, "CellHeading".to_owned());
        pgf_name.insert(PgfKind::TableCell   , "CellBodyLeft".to_owned());
        GeneratorMif {
            core: GeneratorCore::new(1,setting),
            is_rifmux: false,
            multipage: false,
            tbl_idx: 1,
            pgf_name
        }
    }

    fn write_mif_table_cell(&mut self, txt: &str,  pgf_kind: PgfKind) {
        let pgf = self.pgf_name.get(&pgf_kind).unwrap();
        self.write(&format!("\t\t\t\t<Cell <CellContent <Para <PgfTag `{pgf}'>\n"));
        self.write(&Self::mif_lines(txt, 5));
        self.write(         "\t\t\t\t>>>\n");
    }

    fn mif_lines(txt: &str, lvl: usize) -> String {
        let mut mif_txt = String::with_capacity(txt.len());
        let mut lines = txt.lines().peekable();
        while let Some(l) = lines.next() {
            for _ in 0..lvl {mif_txt.push('\t');}
            mif_txt.push_str(&format!("<ParaLine <String `{l}'>"));
            if lines.peek().is_some() {
                mif_txt.push_str("<Char HardReturn>");
            }
            mif_txt.push_str(">\n");
        }
        mif_txt
    }

    fn write_mif_heading(&mut self, txt: &str, idx: usize, pgf_kind: PgfKind) {
        self.push_stash(0,          "\t<Para\n");
        let pgf = self.pgf_name.get(&pgf_kind).unwrap();
        self.push_stash(0, &format!("\t\t<PgfTag `{pgf}'>\n"));
        self.push_stash(0, &format!("\t\t<PgfNumString `{idx}'>\n"));
        self.push_stash(0,          "\t\t<PgfReferenced Yes>\n");
        self.push_stash(0, &format!("\t\t<ParaLine <String `{txt}'>>\n"));
        self.push_stash(0,          "\t>\n");
    }

    fn get_col_width<'a> (&self, kind: TableKind) -> &'a [f32] {
        match kind {
            // RifMux/Page: Offset, Name, Description
            TableKind::Rifmux  => &[2.5, 3.4, 11.1],
            TableKind::Page    => &[2.5, 3.4, 11.1],
            // Register instances: Offset, Name, Reset, Description
            TableKind::RegInst => &[2.5, 3.4, 2.1, 9.4],
            // Fields: Width, Name, Access, Reset, Description
            TableKind::FieldRsvd |
            TableKind::Field   => &[1.4, 3.4, 2.0, 2.1, 8.5],
            // Unused table kind
            _  => &[],
        }
    }

}


impl GeneratorBase for GeneratorMif {

    const EXT : &'static str = "mif";

    fn core(&self) -> &GeneratorCore {
        &self.core
    }

    fn core_mut(&mut self) -> &mut GeneratorCore {
        &mut self.core
    }

}


impl GeneratorDoc for GeneratorMif {
    const HAS_LAYOUT : bool = false;
    const SHOW_TYPE  : bool = false;
    const SHOW_RESET : bool = false;
    const SHOW_SINGLE_REG : bool = false;
    const SHOW_UNUSED : bool = true;

    fn set_rif_info(&mut self, _addr_w: u8, _data_w: u8, nb_page: usize) {
        self.multipage = nb_page > 1;
    }

    fn write_header(&mut self, _name: &str) {
        self.write("<MIFFile 8.00> # Generated by RIF Gen\n");
        self.write("<Tbls\n");
        self.push_stash(0, "<TextFlow\n");
        // self.push_stash(0, &format!("\t<Para <PgfTag `{}'> <ParaLine <ATbl 1>>>\n",
        //     self.pgf_name.get(&PgfKind::Anchor).unwrap()));
    }

    fn write_footer(&mut self, _name: &str) {
        self.write(">\n");
        self.push_stash(0, ">\n");
        self.pop_stash(0);
    }

    fn write_rif_title(&mut self, idx_rif: (&str,usize), desc: &str) {
        // Show title only if sub-paragraph (i.e. RIFmux element)
        // println!("Title RIF {} : {} | rifmux={}", idx_rif.1, idx_rif.0, self.is_rifmux);
        if idx_rif.1 > 0 && self.is_rifmux {
            let title = if desc.is_empty() {idx_rif.0} else {desc};
            self.write_mif_heading(title, idx_rif.1, PgfKind::Heading2);
        } else {
            if !desc.is_empty() {
                self.write_info(desc);
            }
            // Function is first called with index 0 when it is a rifmux
            if idx_rif.1==0 {
                self.is_rifmux = true;
            }
        }
        if !self.is_rifmux {
            self.write_mif_heading("Address Mapping", 1, PgfKind::Heading2);
        }
    }

    fn write_page_title(&mut self, _idx_rif: (&str,usize), idx_page: (&str, usize), desc: (&str, Option<&str>)) {
        if self.is_rifmux {
            return;
        }
        let title = if self.multipage {
            if desc.0.is_empty() {idx_page.0.to_owned()}
            else {format!("{} ({})", desc.0, idx_page.0)}
        } else {
            "Register Description".to_owned()
        };
        self.write_mif_heading(&title, idx_page.1, PgfKind::Heading2);
        if let Some(desc_detail) = desc.1 {
            self.write_info(&self.sanitize(desc_detail));
        }
    }

    fn write_reg_title(&mut self, _idx_rif: (&str,usize), _idx_page: (&str, usize), idx_reg: (&str, usize), desc: &str) {
        let title = if desc.is_empty() {idx_reg.0.to_owned()}
                    else {format!("{} ({})", desc, idx_reg.0)};
        self.write_mif_heading(&title, idx_reg.1, PgfKind::Heading3);
    }

    fn write_table_title(&mut self, kind: TableKind, title: &str, _id: &str) {
        let widths = self.get_col_width(kind);
        let caption = if kind==TableKind::Page {
            if self.multipage {
                format!("{} registers address mapping", title.to_casing(Casing::Title))
            } else {
                "Registers address mapping".to_owned()
            }
        } else {
            self.sanitize(title)
        };
        let pgf_kind = match kind {
            TableKind::Rifmux  => PgfKind::RifmuxTable,
            TableKind::Page    => PgfKind::MappingTable,
            TableKind::RegInst => PgfKind::MappingTable,
            TableKind::Field   => PgfKind::RegTable,
            TableKind::FieldRsvd => PgfKind::RegTable,
            // Unused
            TableKind::Layout  => PgfKind::RegTable,
        };
        //
        self.write(         "\t<Tbl\n");
        self.write(&format!("\t\t<TblID {}>\n", self.tbl_idx));
        self.write(         "\t\t<TblFormat\n");
        self.write(&format!("\t\t\t<TblTag `{}'>\n", self.pgf_name.get(&pgf_kind).unwrap()));
        for (i,w) in widths.iter().enumerate() {
            self.write(&format!("\t\t\t<TblColumn <TblColumnNum {i}> <TblColumnWidth {w} cm>>\n"));
        }
        self.write(         "\t\t>\n");
        self.write(&format!("\t\t<TblNumColumns {}>\n", widths.len()));
        self.write(         "\t\t<TblTitle\n");
        self.write(         "\t\t\t<TblTitleContent\n");
        self.write(&format!("\t\t\t\t<Para <PgfTag `{}'>\n", self.pgf_name.get(&PgfKind::TableTitle).unwrap()));
        self.write(&format!("\t\t\t\t\t<PgfNumString `Table {}. '>\n", self.tbl_idx));
        self.write(         "\t\t\t\t\t<PgfReferenced Yes>\n");
        self.write(&format!("\t\t\t\t\t<ParaLine <String `{caption}'>>\n"));
        self.write(         "\t\t\t\t>\n");
        self.write(         "\t\t\t>\n");
        self.write(         "\t\t> ");
        //
        self.push_stash(0,&format!("\t<Para <PgfTag `{}'> <ParaLine <ATbl {}>>>\n",
                            self.pgf_name.get(&PgfKind::Anchor).unwrap(),
                            self.tbl_idx));

    }

    // Close body and table section
    fn write_table_footer(&mut self, _kind: TableKind) {
        self.write("\t\t>\n");
        self.write("\t>\n");
        self.tbl_idx += 1;
    }

    fn write_table_row_top_header(&mut self, _kind: TableKind) {
        self.write("<TblH\n");
        self.write("\t\t\t<Row\n");
    }

    fn write_table_row_top_footer(&mut self) {
        self.write("\t\t\t>\n");
        self.write("\t\t> <TblBody\n");
    }

    fn write_table_row_header(&mut self, _id: Option<&str>) {
        self.write("\t\t\t<Row\n");
    }

    fn write_table_row_footer(&mut self) {
        self.write("\t\t\t>\n");
    }

    fn write_table_cell_top(&mut self, _kind: (TableKind, CellKind), _span: usize, txt: &str, _id: &str) {
        self.write_mif_table_cell(txt, PgfKind::TableHeading);
    }

    fn write_table_cell(&mut self, kind: (TableKind, CellKind), _span: usize, txt: &str, _id: &str) {
        let txt = if kind.0==TableKind::FieldRsvd {
            match kind.1 {
                CellKind::Inst => "-",
                CellKind::Desc => "Reserved",
                _ => txt,
            }
        } else {txt};
        self.write_mif_table_cell(txt, PgfKind::TableCell);
    }

    fn enum_def_desc(&mut self, def: &EnumDef) -> String {
        let mut desc = String::with_capacity(def.len() * 16);
        let mut enum_iter = def.values.iter().peekable();
        while let Some(entry) = enum_iter.next() {
            let entry_name = self.sanitize(&entry.name);
            let entry_desc = self.sanitize(entry.description.get());
            desc.push_str(&format!("\t\t\t\t\t<ParaLine <String `{:3} - {entry_name} : {entry_desc}'>", entry.value));
            if enum_iter.peek().is_some() {
                desc.push_str("<Char HardReturn>");
            }
            desc.push_str(">\n");
        }
        desc
    }

    fn sanitize(&self, raw: &str) -> String {
        let mut txt = String::with_capacity(raw.len());
        for c in raw.chars() {
            if matches!(c, '\'' | '>') {
                txt.push('\\');
            }
            txt.push(c);
        }
        txt
    }

    fn access_str(kind: &FieldSwKind) -> &str {
        match kind {
            FieldSwKind::W1Clr => "RW1C",
            _ => kind.access_str()
        }
    }

    fn write_info(&mut self, info: &str) {
        let pgf = self.pgf_name.get(&PgfKind::Anchor).unwrap();
        self.push_stash(0, &format!("\t<Para <PgfTag `{pgf}'>\n"));
        self.push_stash(0, &Self::mif_lines(info, 2));
        self.push_stash(0, "\t>\n");
    }
}