#![macro_use]
#![allow(unused_macros)]
use std::{error::Error, fmt::{Debug, Display}};

use crate::rifgen::{context::Context, FieldHwKind};

#[derive(Clone, Debug, Default)]
pub struct ErrorContext {
    pub name: String,
    pub line_num: usize,
    pub cntxt: Context,
}

impl ErrorContext {
    pub fn new() -> ErrorContext {
        ErrorContext { name: "".to_owned(), line_num: 0, cntxt: Context::Top }
    }
    pub fn set(&mut self, line_num: usize, c: Context) {
        self.line_num = line_num;
        self.cntxt = c;
    }
    #[allow(unused)]
    pub fn set_cntxt(&mut self, c: Context) {
        self.cntxt = c;
    }
    pub fn set_name(&mut self, name: String) {
        self.name = name;
    }
}

thread_local!(pub static ERROR_CONTEXT: std::cell::RefCell<ErrorContext>  = std::cell::RefCell::new( ErrorContext::new() ) );
macro_rules! err_set_context {
    ($n:expr, $c:expr) => {{ ERROR_CONTEXT.with(|e| {e.borrow_mut().set($n,$c)}) }};
    ($c:expr) => {{ ERROR_CONTEXT.with(|e| {e.borrow_mut().set_cntxt($c)}) }};
}

macro_rules! err_set_name {
    ($n:expr) => {{ ERROR_CONTEXT.with(|e| {e.borrow_mut().set_name($n)}) }};
}

/// Error kind generated by parser/compiler
#[derive(PartialEq, Clone, Debug)]
pub enum RifErrorKind {
    /// File IO error
    Io,
    /// Parsing error
    Parse,
    /// Address width not supported
    AddrWidth,
    /// Instance address not aligned with RIF data width
    AddrUnaligned,
    /// Field Kind incompatibility
    FieldKind,
    /// Interrupt setting in non interrupt register
    NotIntr,
    /// Missing register definition
    MissingDef,
    /// Unsupported Feature
    Unsupported,
    /// Duplicated register/field definition
    Duplicated,
    /// Use of reserved keyword for a name
    Keyword,
    /// Generic errror
    Generic,
}

/// Error information generated by parser/compiler
#[derive(Clone, Debug, PartialEq)]
pub struct RifError {
    /// Kind of error
    pub kind: RifErrorKind,
    /// Name of propertyregister/... which trigger the error
    pub name: String,
    //// Line number where error was found (mainly for parsing)
    pub line_num: usize,
    /// More details about the error
    pub txt: String,
}

impl Error for RifError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        None
    }
}

impl From<std::io::Error> for RifError {
    fn from(cause: std::io::Error) -> RifError {
        RifError{
            kind:RifErrorKind::Io,
            name: "".to_owned(),
            line_num: 0,
            txt: format!("{cause}")
        }
    }
}

impl From<winnow::error::ParseError<&str, winnow::error::ContextError>> for RifError {
    fn from(cause: winnow::error::ParseError<&str, winnow::error::ContextError> ) -> RifError {
        RifError{
            kind:RifErrorKind::Parse,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: format!("Unable to parse {} elements\n{}", ERROR_CONTEXT.with(|c| c.borrow().cntxt.to_owned()), cause)
        }
    }
}

impl From< winnow::error::ErrMode<winnow::error::ContextError> > for RifError {
    fn from(cause: winnow::error::ErrMode<winnow::error::ContextError> ) -> RifError {
        let err = match cause {
            winnow::error::ErrMode::Incomplete(_) => None,
            winnow::error::ErrMode::Backtrack(e) => e.context().last().cloned(),
            winnow::error::ErrMode::Cut(e) => e.context().last().cloned(),
        };
        RifError{
            kind:RifErrorKind::Parse,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: format!("{} | {}", ERROR_CONTEXT.with(|c| c.borrow().cntxt.to_owned()), err.unwrap_or(winnow::error::StrContext::Label("")))
        }
    }
}

impl From<RifErrorKind> for RifError {
    fn from(kind: RifErrorKind ) -> RifError {
        RifError{
            kind,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: format!("{}", ERROR_CONTEXT.with(|c| c.borrow().cntxt.to_owned()))
        }
    }
}

impl From<String> for RifError {
    fn from(txt: String ) -> RifError {
        RifError{
            name: "".to_owned(),
            kind: RifErrorKind::Generic,
            line_num: 0,
            txt
        }
    }
}

impl RifError {

    pub fn missing_def(name: &str) -> Self {
        RifError {
            kind: RifErrorKind::MissingDef,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: name.to_owned()
        }
    }

    pub fn keyword(name: &str) -> Self {
        RifError {
            kind: RifErrorKind::Keyword,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: name.to_owned()
        }
    }

    pub fn unsupported(cntxt: Context, line: &str) -> Self {
        RifError {
            kind: RifErrorKind::Unsupported,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: format!("{cntxt} in {} | '{line}'",  ERROR_CONTEXT.with(|c| c.borrow().cntxt.to_owned()))
        }
    }

    pub fn duplicated(cntxt: Context, name: &str) -> Self {
        RifError {
            kind: RifErrorKind::Duplicated,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: format!("{} {}",cntxt, name.to_owned())
        }
    }

    pub fn field_kind<K>(kind: K, hw_kind: &[FieldHwKind]) -> Self
        where K: Debug
    {
        RifError {
            kind: RifErrorKind::FieldKind,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt:  format!("{kind:?} and {hw_kind:?}")
        }
    }

    pub fn generic(txt: &str) -> Self {
        RifError {
            kind: RifErrorKind::Generic,
            name: ERROR_CONTEXT.with(|c| c.borrow().name.to_owned()),
            line_num: ERROR_CONTEXT.with(|c| c.borrow().line_num),
            txt: txt.to_owned()
        }
    }
}

impl Display for RifError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.kind {
            RifErrorKind::Io            => write!(f, "IO exception: {}", self.txt),
            RifErrorKind::Parse         => write!(f, "{}.{} | {}", self.name, self.line_num, self.txt),
            RifErrorKind::AddrWidth     => write!(f, "{}.{} | Address width must be a power of 2 * 8 bits", self.name, self.line_num),
            RifErrorKind::AddrUnaligned => write!(f, "{}.{} | Address not aligned with data width", self.name, self.line_num),
            RifErrorKind::FieldKind     => write!(f, "{}.{} | incompatible field kind {}", self.name, self.line_num, self.txt),
            RifErrorKind::NotIntr       => write!(f, "{}.{} | Trying to set interrupt properties while register is not an interrupt", self.name, self.line_num),
            RifErrorKind::MissingDef    => write!(f, "{}.{} | Missing register definition for {}", self.name, self.line_num, self.txt),
            RifErrorKind::Unsupported   => write!(f, "{}.{} | Unsupported feature {}", self.name, self.line_num, self.txt),
            RifErrorKind::Duplicated    => write!(f, "{}.{} | {} duplicated !", self.name, self.line_num, self.txt),
            RifErrorKind::Keyword       => write!(f, "{}.{} | Field name '{}' is a reserved keyword !", self.name, self.line_num, self.txt),
            RifErrorKind::Generic       => write!(f, "{}", self.txt),
        }
    }
}

impl From<RifError> for String {
    fn from(value: RifError) -> Self {
        format!("{value}")
    }
}